---
- name: Deploy Docker Container to Multiple Servers
  hosts: webservers  # ← All servers in [webservers] group!
  become: yes

  tasks:
    - name: Ensure app directory exists
      file:
        path: /home/ec2-user/poc-7-github-actions-docker-ansible
        state: directory

    - name: Pull latest code from GitHub
      git:
        repo: 'https://github.com/soumyapatil02/poc-7-github-actions-docker-ansible.git'
        dest: /home/ec2-user/poc-7-github-actions-docker-ansible
        version: main
        force: yes

    - name: Stop old container if exists
      shell: docker stop poc7-container || true

    - name: Remove old container if exists
      shell: docker rm poc7-container || true

    - name: Remove old image if exists
      shell: docker rmi poc7-image || true

    - name: Build Docker image
      shell: docker build -t poc7-image /home/ec2-user/poc-7-github-actions-docker-ansible

    - name: Run new container
      shell: docker run -d --name poc7-container --restart always -p 80:80 poc7-image