name: POC-7 CI-CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH & Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to your app directory
          cd /home/ec2-user/poc-7-github-actions-docker-ansible
          
          # Pull latest code from GitHub
          git pull origin main
          
          # Stop and remove old container
          docker stop poc7-container || true
          docker rm poc7-container || true
          docker rmi poc7-image || true
          
          # Build new Docker image
          docker build -t poc7-image .
          
          # Run new container
          docker run -d --name poc7-container --restart always -p 80:80 poc7-image